services:
    mysql:
      container_name: mysql
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: safebuy
        MYSQL_USER: safebuy
        MYSQL_PASSWORD: safebuy
        MYSQL_DATABASE: safebuy
      volumes:
        - mysql_data:/var/lib/mysql
      restart: unless-stopped

volumes:
  mysql_data: