services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin
    ports:
      - "9411:9411"

  marketplace:
    container_name: marketplace
    image: haginus/marketplace
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: kube

volumes:
  mysql_data: