services:
  mysql:
    container_name: mysql
    image: mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin
    ports:
      - "9411:9411"

#  config-server:
#    container_name: config-server
#    image: haginus/config-server
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_PROFILES_ACTIVE: kube

  marketplace:
    container_name: marketplace
    image: haginus/marketplace
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: kube
    depends_on:
      - mysql
      - zipkin

#  payment:
#    container_name: payment
#    image: haginus/payment
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_PROFILES_ACTIVE: kube
#
#  user:
#    container_name: user
#    image: haginus/user
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_PROFILES_ACTIVE: kube

volumes:
  mysql_data: