spring:
  datasource:
    url: jdbc:mysql://mysql:3306/marketplace?createDatabaseIfNotExist=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  config:
    import: optional:configserver:http://config-server:8070
  zipkin:
    baseUrl: http://zipkin:9411

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: false
    service-url:
      defaultZone: http://eurika:8071/eureka