server:
  port: 8083
spring:
  application:
    name: payment
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/payment?createDatabaseIfNotExist=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8070

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: payment
    description: managing payments
    version: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8071/eureka