apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safebuy-ingress
spec:
  rules:
    - http:
        paths:
          - path: /marketplace/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: marketplace
                port:
                  number: 8082
          - path: /payment/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: payment
                port:
                  number: 8083
          - path: /user/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: user
                port:
                  number: 8084