server:
  port: 8070
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haginus/awbd_config.git
          clone-on-start: true
          default-label: main

